In [30]:
import tensorflow as tf
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
dataset = pd.read_csv('/content/train.csv')

In [4]:
dataset

          id Driver      Compound  ... RaceProgress  Position_Change  PitNextLap
0          0   D109          HARD  ...     0.714286              5.0         1.0
1          1   D086          HARD  ...     0.346154             -3.0         0.0
2          2    ZON          HARD  ...     0.819444              3.0         1.0
3          3    SPE        MEDIUM  ...     0.076923              0.0         0.0
4          4   D019          HARD  ...     0.361111              3.0         0.0
...      ...    ...           ...  ...          ...              ...         ...
43238  43238    LEC  INTERMEDIATE  ...     0.051282            -16.0         1.0
43239  43239   D184          HARD  ...     0.263158              0.0         0.0
43240  43240   D109        MEDIUM  ...     0.083333              2.0         0.0
43241  43241   D186        MEDIUM  ...     0.155844            -10.0         0.0
43242   4324    NaN           NaN  ...          NaN              NaN         NaN

[43243 rows x 16 columns]

In [12]:
print(dataset[((dataset['PitNextLap'] == 1) & (dataset['LapTime_Delta'] < 0))].shape)
print(dataset[((dataset['PitNextLap'] == 1) & (dataset['LapTime_Delta'] > 0))].shape)

(5980, 16)
(2421, 16)

In [13]:
dataset.describe()

                 id          Year  ...  Position_Change    PitNextLap
count  43243.000000  43242.000000  ...     43242.000000  43242.000000
mean   21620.100016   2023.521484  ...         0.099533      0.199043
std    12483.167276      1.025569  ...         4.015320      0.399285
min        0.000000   2022.000000  ...       -18.000000      0.000000
25%    10809.500000   2023.000000  ...        -1.000000      0.000000
50%    21620.000000   2023.000000  ...         0.000000      0.000000
75%    32430.500000   2024.000000  ...         2.000000      0.000000
max    43241.000000   2025.000000  ...        17.000000      1.000000

[8 rows x 13 columns]

In [14]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43243 entries, 0 to 43242
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      43243 non-null  int64
 1   Driver                  43242 non-null  object
 2   Compound                43242 non-null  object
 3   Race                    43242 non-null  object
 4   Year                    43242 non-null  float64
 5   PitStop                 43242 non-null  float64
 6   LapNumber               43242 non-null  float64
 7   Stint                   43242 non-null  float64
 8   TyreLife                43242 non-null  float64
 9   Position                43242 non-null  float64
 10  LapTime (s)             43242 non-null  float64
 11  LapTime_Delta           43242 non-null  float64
 12  Cumulative_Degradation  43242 non-null  float64
 13  RaceProgress            43242 non-null  float64
 14  Position_Change         43242 non-null  float64
 15  PitNextLap              43242 non-null  float64
dtypes: float64(12), int64(1), object(3)
memory usage: 5.3+ MB

In [19]:
dataset.dropna(inplace = True)

In [20]:
dataset.isna().sum()

id                        0
Driver                    0
Compound                  0
Race                      0
Year                      0
PitStop                   0
LapNumber                 0
Stint                     0
TyreLife                  0
Position                  0
LapTime (s)               0
LapTime_Delta             0
Cumulative_Degradation    0
RaceProgress              0
Position_Change           0
PitNextLap                0
dtype: int64

In [29]:
print(dataset['Race'].unique())
len(dataset['Race'].unique())

['Canadian Grand Prix' 'Dutch Grand Prix' 'Austrian Grand Prix'
 'Pre-Season Testing' 'Azerbaijan Grand Prix' 'Saudi Arabian Grand Prix'
 'Belgian Grand Prix' 'United States Grand Prix' 'Italian Grand Prix'
 'Hungarian Grand Prix' 'Japanese Grand Prix' 'São Paulo Grand Prix'
 'Bahrain Grand Prix' 'Las Vegas Grand Prix' 'Monaco Grand Prix'
 'British Grand Prix' 'Australian Grand Prix' 'Spanish Grand Prix'
 'Miami Grand Prix' 'French Grand Prix' 'Abu Dhabi Grand Prix'
 'Chinese Grand Prix' 'Mexico City Grand Prix' 'Emilia Romagna Grand Prix'
 'Singapore Grand Prix' 'Qatar Grand Prix']

26

In [33]:
dataset.drop(columns=['id', 'Driver'], inplace = True)

In [36]:
print(dataset.columns)
for column in dataset.columns:
  print(column, ': ', dataset[column].dtype)

Index(['Compound', 'Race', 'Year', 'PitStop', 'LapNumber', 'Stint', 'TyreLife',
       'Position', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation',
       'RaceProgress', 'Position_Change', 'PitNextLap'],
      dtype='object')
Compound :  object
Race :  object
Year :  float64
PitStop :  float64
LapNumber :  float64
Stint :  float64
TyreLife :  float64
Position :  float64
LapTime (s) :  float64
LapTime_Delta :  float64
Cumulative_Degradation :  float64
RaceProgress :  float64
Position_Change :  float64
PitNextLap :  float64

In [39]:
x = dataset.drop(columns = ['PitNextLap'])
y = dataset['PitNextLap']

In [47]:
y = y.astype('int32')

In [49]:
x

           Compound                   Race  ...  RaceProgress  Position_Change
0              HARD    Canadian Grand Prix  ...      0.714286              5.0
1              HARD       Dutch Grand Prix  ...      0.346154             -3.0
2              HARD    Austrian Grand Prix  ...      0.819444              3.0
3            MEDIUM     Pre-Season Testing  ...      0.076923              0.0
4              HARD  Azerbaijan Grand Prix  ...      0.361111              3.0
...             ...                    ...  ...           ...              ...
43237          HARD     Pre-Season Testing  ...      0.564103              0.0
43238  INTERMEDIATE    Canadian Grand Prix  ...      0.051282            -16.0
43239          HARD       Miami Grand Prix  ...      0.263158              0.0
43240        MEDIUM     Pre-Season Testing  ...      0.083333              2.0
43241        MEDIUM       Dutch Grand Prix  ...      0.155844            -10.0

[43242 rows x 13 columns]

In [51]:
one_hot_encode_cols = ['Compound', 'Race']

In [52]:
from sklearn.preprocessing import OneHotEncoder

In [53]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([
    ('one_hot_endcoing', OneHotEncoder(), one_hot_encode_cols),
], remainder='passthrough')

In [56]:
x = ct.fit_transform(x)

In [62]:
cols = ct.get_feature_names_out()
x = pd.DataFrame(x, columns = (name.split('__')[1] for name in cols))

In [63]:
x

       Compound_HARD  Compound_INTERMEDIATE  ...  RaceProgress  Position_Change
0                1.0                    0.0  ...      0.714286              5.0
1                1.0                    0.0  ...      0.346154             -3.0
2                1.0                    0.0  ...      0.819444              3.0
3                0.0                    0.0  ...      0.076923              0.0
4                1.0                    0.0  ...      0.361111              3.0
...              ...                    ...  ...           ...              ...
43237            1.0                    0.0  ...      0.564103              0.0
43238            0.0                    1.0  ...      0.051282            -16.0
43239            1.0                    0.0  ...      0.263158              0.0
43240            0.0                    0.0  ...      0.083333              2.0
43241            0.0                    0.0  ...      0.155844            -10.0

[43242 rows x 42 columns]

In [64]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2, stratify=y)

In [75]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

In [67]:
models = [
    ('Random Forest', RandomForestClassifier(n_estimators = 500)),
    ('Decision Tree', DecisionTreeClassifier()),
    ('Logistic Regression', LogisticRegression()),
    ('KNN', KNeighborsClassifier()),
    ('SVM', SVC()),
    ('XGBoost', XGBClassifier()),
]

In [68]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [71]:
kf = KFold(n_splits = 5, shuffle = True, random_state = 42)
for (name, model) in models:
  scores = cross_val_score(model, x, y, cv = kf, scoring = 'accuracy')
  print(name, scores.mean(), scores.std())

KeyboardInterrupt:

In [80]:
kf = KFold(n_splits = 5, shuffle = True, random_state = 42)
cross_val_score(RandomForestClassifier(n_estimators = 200), x.drop(columns = ['Year']), y, cv = kf, scoring = 'accuracy').mean()

np.float64(0.8815965768047704)