In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [ ]:
dataset = pd.read_csv('/content/insurance.csv')

In [ ]:
dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
insurance = pd.get_dummies(dataset, dtype = 'int16')

In [ ]:
insurance

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,1,0,0,1,0,0,0,1
1,18,33.770,1,1725.55230,0,1,1,0,0,0,1,0
2,28,33.000,3,4449.46200,0,1,1,0,0,0,1,0
3,33,22.705,0,21984.47061,0,1,1,0,0,1,0,0
4,32,28.880,0,3866.85520,0,1,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,0,1,1,0,0,1,0,0
1334,18,31.920,0,2205.98080,1,0,1,0,1,0,0,0
1335,18,36.850,0,1629.83350,1,0,1,0,0,0,1,0
1336,21,25.800,0,2007.94500,1,0,1,0,0,0,0,1
1337,61,29.070,0,29141.36030,1,0,0,1,0,1,0,0

In [ ]:
x = insurance.drop('charges', axis = 1)
y = insurance['charges']

In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [ ]:
tf.random.set_seed(42)

insurance_model = tf.keras.Sequential([
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
])

insurance_model.compile(loss = tf.keras.losses.mae,
                        optimizer = tf.keras.optimizers.SGD(),
                        metrics=['mae'])

insurance_model.fit(xtrain, ytrain, epochs=100)

Epoch 1/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 8596.8047 - mae: 8596.8047
Epoch 2/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7536.9961 - mae: 7536.9961
Epoch 3/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7650.1660 - mae: 7650.1660
Epoch 4/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7471.2529 - mae: 7471.2529
Epoch 5/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7527.1387 - mae: 7527.1387
Epoch 6/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7544.0576 - mae: 7544.0576
Epoch 7/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7429.7256 - mae: 7429.7256
Epoch 8/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7463.2886 - mae: 7463.2886
Epoch 9/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7686.7183 - mae: 7686.7183
Epoch 10/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7642.0640 - mae: 7642.0640
Epoch 11/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7722.5938 - mae: 7722.5938
Epoch 12/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7764.9927 - mae: 7764.9927
Epoch 13/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7493.3643 - mae: 7493.3643
Epoch 14/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7432.7495 - mae: 7432.7495
Epoch 15/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7655.7461 - mae: 7655.7461
Epoch 16/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7653.9302 - mae: 7653.9302
Epoch 17/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7700.1997 - mae: 7700.1997
Epoch 18/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7453.3677 - mae: 7453.3677
Epoch 19/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7472.8330 - mae: 7472.8330
Epoch 20/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7729.2598 - mae: 7729.2598
Epoch 21/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7553.8711 - mae: 7553.8711
Epoch 22/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7584.7520 - mae: 7584.7520
Epoch 23/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7595.2236 - mae: 7595.2236
Epoch 24/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7523.3291 - mae: 7523.3291
Epoch 25/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7677.8267 - mae: 7677.8267
Epoch 26/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7354.1094 - mae: 7354.1094
Epoch 27/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7384.3008 - mae: 7384.3008
Epoch 28/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7573.2974 - mae: 7573.2974
Epoch 29/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7375.9346 - mae: 7375.9346
Epoch 30/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7534.3276 - mae: 7534.3276
Epoch 31/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7597.5845 - mae: 7597.5845
Epoch 32/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7628.5381 - mae: 7628.5381
Epoch 33/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7474.3032 - mae: 7474.3032
Epoch 34/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7573.1699 - mae: 7573.1699
Epoch 35/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7342.9092 - mae: 7342.9092
Epoch 36/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7342.7310 - mae: 7342.7310
Epoch 37/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7537.3677 - mae: 7537.3677
Epoch 38/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7426.3354 - mae: 7426.3354
Epoch 39/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7640.9937 - mae: 7640.9937
Epoch 40/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7553.2144 - mae: 7553.2144
Epoch 41/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7568.4048 - mae: 7568.4048
Epoch 42/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7214.7432 - mae: 7214.7432
Epoch 43/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7221.5942 - mae: 7221.5942
Epoch 44/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7489.8716 - mae: 7489.8716
Epoch 45/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7484.5713 - mae: 7484.5713
Epoch 46/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7428.0186 - mae: 7428.0186
Epoch 47/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7302.7690 - mae: 7302.7690
Epoch 48/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7171.2227 - mae: 7171.2227
Epoch 49/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7483.0815 - mae: 7483.0815
Epoch 50/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7260.2812 - mae: 7260.2812
Epoch 51/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7317.7480 - mae: 7317.7480
Epoch 52/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7535.2554 - mae: 7535.2554
Epoch 53/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7481.0986 - mae: 7481.0986
Epoch 54/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7468.7520 - mae: 7468.7520
Epoch 55/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7339.5962 - mae: 7339.5962
Epoch 56/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7375.6846 - mae: 7375.6846
Epoch 57/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7361.9727 - mae: 7361.9727
Epoch 58/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7491.9541 - mae: 7491.9541
Epoch 59/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7306.2163 - mae: 7306.2163
Epoch 60/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7405.7617 - mae: 7405.7617
Epoch 61/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7451.1748 - mae: 7451.1748
Epoch 62/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7428.8267 - mae: 7428.8267
Epoch 63/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7419.1895 - mae: 7419.1895
Epoch 64/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7385.2739 - mae: 7385.2739
Epoch 65/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7218.2021 - mae: 7218.2021
Epoch 66/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7358.0000 - mae: 7358.0000
Epoch 67/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7367.3721 - mae: 7367.3721
Epoch 68/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7096.4365 - mae: 7096.4365
Epoch 69/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7449.1548 - mae: 7449.1548
Epoch 70/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7267.1284 - mae: 7267.1284
Epoch 71/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7390.0933 - mae: 7390.0933
Epoch 72/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7363.4854 - mae: 7363.4854
Epoch 73/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7512.2227 - mae: 7512.2227
Epoch 74/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7318.1255 - mae: 7318.1255
Epoch 75/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7438.3491 - mae: 7438.3491
Epoch 76/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7377.4614 - mae: 7377.4614
Epoch 77/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7159.7637 - mae: 7159.7637
Epoch 78/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7122.1460 - mae: 7122.1460
Epoch 79/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7258.5693 - mae: 7258.5693
Epoch 80/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7367.1948 - mae: 7367.1948
Epoch 81/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7329.9048 - mae: 7329.9048
Epoch 82/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7228.3135 - mae: 7228.3135
Epoch 83/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7300.9194 - mae: 7300.9194
Epoch 84/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7330.4868 - mae: 7330.4868
Epoch 85/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7333.9971 - mae: 7333.9971
Epoch 86/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7186.6704 - mae: 7186.6704
Epoch 87/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7175.5415 - mae: 7175.5415
Epoch 88/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7254.2031 - mae: 7254.2031
Epoch 89/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7236.1187 - mae: 7236.1187
Epoch 90/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7048.5723 - mae: 7048.5723
Epoch 91/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7456.3198 - mae: 7456.3198
Epoch 92/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7062.0981 - mae: 7062.0981
Epoch 93/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7300.4126 - mae: 7300.4126
Epoch 94/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7205.1025 - mae: 7205.1025
Epoch 95/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7341.1240 - mae: 7341.1240
Epoch 96/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6966.9658 - mae: 6966.9658
Epoch 97/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7411.8398 - mae: 7411.8398
Epoch 98/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7322.6274 - mae: 7322.6274
Epoch 99/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7417.0503 - mae: 7417.0503
Epoch 100/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7243.8125 - mae: 7243.8125

In [ ]:
insurance_model.evaluate(xtest, ytest)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 8118.4116 - mae: 8118.4116

[8118.41162109375, 8118.41162109375]

In [ ]:
tf.random.set_seed(42)

insurance_model = tf.keras.Sequential([
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
])

insurance_model.compile(loss = tf.keras.losses.mae,
                        optimizer = tf.keras.optimizers.Adam(learning_rate=0.001),
                        metrics=['mae'])

insurance_model.fit(xtrain, ytrain, epochs=100)

Epoch 1/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 13291.6309 - mae: 13291.6309
Epoch 2/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13138.7012 - mae: 13138.7012
Epoch 3/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12813.8340 - mae: 12813.8340
Epoch 4/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12174.8643 - mae: 12174.8643
Epoch 5/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11086.5967 - mae: 11086.5967
Epoch 6/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9653.1338 - mae: 9653.1338
Epoch 7/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8284.9307 - mae: 8284.9307
Epoch 8/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7557.5190 - mae: 7557.5190
Epoch 9/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7430.8105 - mae: 7430.8105
Epoch 10/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7405.7578 - mae: 7405.7578
Epoch 11/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7386.0586 - mae: 7386.0586
Epoch 12/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7366.1143 - mae: 7366.1143
Epoch 13/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7346.2036 - mae: 7346.2036
Epoch 14/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7325.7207 - mae: 7325.7207
Epoch 15/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7305.0557 - mae: 7305.0557
Epoch 16/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7284.5835 - mae: 7284.5835
Epoch 17/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7263.5405 - mae: 7263.5405
Epoch 18/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7242.2080 - mae: 7242.2080
Epoch 19/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7220.7896 - mae: 7220.7896
Epoch 20/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7198.9214 - mae: 7198.9214
Epoch 21/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7176.4346 - mae: 7176.4346
Epoch 22/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7153.4893 - mae: 7153.4893
Epoch 23/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7129.6797 - mae: 7129.6797
Epoch 24/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7105.3394 - mae: 7105.3394
Epoch 25/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7080.5103 - mae: 7080.5103
Epoch 26/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7055.3423 - mae: 7055.3423
Epoch 27/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7030.3022 - mae: 7030.3022
Epoch 28/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7004.1138 - mae: 7004.1138
Epoch 29/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6976.9121 - mae: 6976.9121
Epoch 30/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6949.3765 - mae: 6949.3765
Epoch 31/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6921.1621 - mae: 6921.1621
Epoch 32/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6891.9272 - mae: 6891.9272
Epoch 33/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6862.7017 - mae: 6862.7017
Epoch 34/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6832.5840 - mae: 6832.5840
Epoch 35/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6801.3945 - mae: 6801.3945
Epoch 36/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6768.9092 - mae: 6768.9092
Epoch 37/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6735.8096 - mae: 6735.8096
Epoch 38/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6701.4937 - mae: 6701.4937
Epoch 39/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6668.3784 - mae: 6668.3784
Epoch 40/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6634.6582 - mae: 6634.6582
Epoch 41/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6601.7178 - mae: 6601.7178
Epoch 42/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6570.5640 - mae: 6570.5640
Epoch 43/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6542.1504 - mae: 6542.1504
Epoch 44/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6517.6001 - mae: 6517.6001
Epoch 45/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6497.3750 - mae: 6497.3750
Epoch 46/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6480.5405 - mae: 6480.5405
Epoch 47/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6465.0996 - mae: 6465.0996
Epoch 48/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6450.6504 - mae: 6450.6504
Epoch 49/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6436.9839 - mae: 6436.9839
Epoch 50/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6424.0688 - mae: 6424.0688
Epoch 51/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6411.1743 - mae: 6411.1743
Epoch 52/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6398.2593 - mae: 6398.2593
Epoch 53/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6385.7227 - mae: 6385.7227
Epoch 54/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6373.1421 - mae: 6373.1421
Epoch 55/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6360.2017 - mae: 6360.2017
Epoch 56/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6347.1621 - mae: 6347.1621
Epoch 57/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6333.7202 - mae: 6333.7202
Epoch 58/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6320.1665 - mae: 6320.1665
Epoch 59/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6306.2119 - mae: 6306.2119
Epoch 60/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6291.9238 - mae: 6291.9238
Epoch 61/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6277.2983 - mae: 6277.2983
Epoch 62/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6262.4556 - mae: 6262.4556
Epoch 63/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6247.5747 - mae: 6247.5747
Epoch 64/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6231.9170 - mae: 6231.9170
Epoch 65/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6215.8574 - mae: 6215.8574
Epoch 66/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6199.5645 - mae: 6199.5645
Epoch 67/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6182.7900 - mae: 6182.7900
Epoch 68/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6165.4619 - mae: 6165.4619
Epoch 69/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6147.5977 - mae: 6147.5977
Epoch 70/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6129.5601 - mae: 6129.5601
Epoch 71/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6111.0781 - mae: 6111.0781
Epoch 72/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6091.8711 - mae: 6091.8711
Epoch 73/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6071.8140 - mae: 6071.8140
Epoch 74/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6051.1279 - mae: 6051.1279
Epoch 75/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6030.0527 - mae: 6030.0527
Epoch 76/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6008.1904 - mae: 6008.1904
Epoch 77/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5985.6685 - mae: 5985.6685
Epoch 78/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5962.1748 - mae: 5962.1748
Epoch 79/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5938.1704 - mae: 5938.1704
Epoch 80/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5912.3726 - mae: 5912.3726
Epoch 81/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5885.8359 - mae: 5885.8359
Epoch 82/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5858.3130 - mae: 5858.3130
Epoch 83/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5830.2065 - mae: 5830.2065
Epoch 84/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5801.3281 - mae: 5801.3281
Epoch 85/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5770.7422 - mae: 5770.7422
Epoch 86/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5738.0840 - mae: 5738.0840
Epoch 87/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5704.7051 - mae: 5704.7051
Epoch 88/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5669.0259 - mae: 5669.0259
Epoch 89/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5632.6533 - mae: 5632.6533
Epoch 90/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5595.2236 - mae: 5595.2236
Epoch 91/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5555.2446 - mae: 5555.2446
Epoch 92/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5513.9180 - mae: 5513.9180
Epoch 93/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5470.0503 - mae: 5470.0503
Epoch 94/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5424.9067 - mae: 5424.9067
Epoch 95/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5375.8320 - mae: 5375.8320
Epoch 96/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5325.8296 - mae: 5325.8296
Epoch 97/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5271.6206 - mae: 5271.6206
Epoch 98/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5218.1812 - mae: 5218.1812
Epoch 99/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5160.5298 - mae: 5160.5298
Epoch 100/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5099.6128 - mae: 5099.6128

In [ ]:
insurance_model.evaluate(xtest, ytest)

9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - loss: 4977.2729 - mae: 4977.2729

[4977.27294921875, 4977.27294921875]

In [ ]:
tf.random.set_seed(42)

insurance_model = tf.keras.Sequential([
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
])

insurance_model.compile(loss = tf.keras.losses.mae,
                        optimizer = tf.keras.optimizers.Adam(),
                        metrics=['mae'])

history = insurance_model.fit(xtrain, ytrain, epochs=500)

Epoch 1/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 13294.5225 - mae: 13294.5225
Epoch 2/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13126.2793 - mae: 13126.2793
Epoch 3/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12772.4023 - mae: 12772.4023
Epoch 4/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12078.3936 - mae: 12078.3936
Epoch 5/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10915.8125 - mae: 10915.8125
Epoch 6/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9441.0557 - mae: 9441.0557
Epoch 7/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8104.5962 - mae: 8104.5962
Epoch 8/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7498.5654 - mae: 7498.5654
Epoch 9/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7413.5601 - mae: 7413.5601
Epoch 10/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7390.2549 - mae: 7390.2549
Epoch 11/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7369.7563 - mae: 7369.7563
Epoch 12/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7348.7148 - mae: 7348.7148
Epoch 13/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7327.5552 - mae: 7327.5552
Epoch 14/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7306.1562 - mae: 7306.1562
Epoch 15/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7284.8672 - mae: 7284.8672
Epoch 16/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7262.8945 - mae: 7262.8945
Epoch 17/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7240.5488 - mae: 7240.5488
Epoch 18/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7218.0894 - mae: 7218.0894
Epoch 19/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7194.9575 - mae: 7194.9575
Epoch 20/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7171.3560 - mae: 7171.3560
Epoch 21/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7147.0034 - mae: 7147.0034
Epoch 22/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7121.9561 - mae: 7121.9561
Epoch 23/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7096.1191 - mae: 7096.1191
Epoch 24/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7069.8887 - mae: 7069.8887
Epoch 25/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7043.2920 - mae: 7043.2920
Epoch 26/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7016.3477 - mae: 7016.3477
Epoch 27/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6988.2612 - mae: 6988.2612
Epoch 28/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6959.1050 - mae: 6959.1050
Epoch 29/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6929.6069 - mae: 6929.6069
Epoch 30/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6898.6333 - mae: 6898.6333
Epoch 31/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6867.6309 - mae: 6867.6309
Epoch 32/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6836.2397 - mae: 6836.2397
Epoch 33/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6803.7832 - mae: 6803.7832
Epoch 34/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6769.7144 - mae: 6769.7144
Epoch 35/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6734.8291 - mae: 6734.8291
Epoch 36/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6699.0552 - mae: 6699.0552
Epoch 37/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6664.0757 - mae: 6664.0757
Epoch 38/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6628.9033 - mae: 6628.9033
Epoch 39/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6595.3477 - mae: 6595.3477
Epoch 40/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6563.2744 - mae: 6563.2744
Epoch 41/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6535.6919 - mae: 6535.6919
Epoch 42/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6512.1797 - mae: 6512.1797
Epoch 43/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6492.9175 - mae: 6492.9175
Epoch 44/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6476.2417 - mae: 6476.2417
Epoch 45/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6461.1777 - mae: 6461.1777
Epoch 46/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6446.7900 - mae: 6446.7900
Epoch 47/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6433.5034 - mae: 6433.5034
Epoch 48/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6420.3110 - mae: 6420.3110
Epoch 49/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6406.9946 - mae: 6406.9946
Epoch 50/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6394.1104 - mae: 6394.1104
Epoch 51/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6381.2593 - mae: 6381.2593
Epoch 52/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6368.0381 - mae: 6368.0381
Epoch 53/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6354.7988 - mae: 6354.7988
Epoch 54/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6341.1367 - mae: 6341.1367
Epoch 55/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6327.4517 - mae: 6327.4517
Epoch 56/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6313.2607 - mae: 6313.2607
Epoch 57/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6298.7754 - mae: 6298.7754
Epoch 58/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6283.8926 - mae: 6283.8926
Epoch 59/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6269.0488 - mae: 6269.0488
Epoch 60/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6253.6006 - mae: 6253.6006
Epoch 61/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6237.8608 - mae: 6237.8608
Epoch 62/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6221.5635 - mae: 6221.5635
Epoch 63/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6205.0142 - mae: 6205.0142
Epoch 64/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6187.7524 - mae: 6187.7524
Epoch 65/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6170.0547 - mae: 6170.0547
Epoch 66/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6152.2568 - mae: 6152.2568
Epoch 67/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6133.9551 - mae: 6133.9551
Epoch 68/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6114.7729 - mae: 6114.7729
Epoch 69/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6095.3667 - mae: 6095.3667
Epoch 70/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6075.4097 - mae: 6075.4097
Epoch 71/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6054.3149 - mae: 6054.3149
Epoch 72/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6032.8584 - mae: 6032.8584
Epoch 73/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6010.8638 - mae: 6010.8638
Epoch 74/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5987.3159 - mae: 5987.3159
Epoch 75/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5963.3750 - mae: 5963.3750
Epoch 76/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5938.8315 - mae: 5938.8315
Epoch 77/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5912.5703 - mae: 5912.5703
Epoch 78/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5885.4399 - mae: 5885.4399
Epoch 79/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5857.4956 - mae: 5857.4956
Epoch 80/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5828.6685 - mae: 5828.6685
Epoch 81/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5798.8804 - mae: 5798.8804
Epoch 82/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5767.1357 - mae: 5767.1357
Epoch 83/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5734.0942 - mae: 5734.0942
Epoch 84/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5700.0703 - mae: 5700.0703
Epoch 85/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5665.9971 - mae: 5665.9971
Epoch 86/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5627.3228 - mae: 5627.3228
Epoch 87/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5588.3877 - mae: 5588.3877
Epoch 88/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5547.7646 - mae: 5547.7646
Epoch 89/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5504.7837 - mae: 5504.7837
Epoch 90/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5460.4565 - mae: 5460.4565
Epoch 91/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5413.3726 - mae: 5413.3726
Epoch 92/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5365.9839 - mae: 5365.9839
Epoch 93/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5312.8647 - mae: 5312.8647
Epoch 94/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5257.9839 - mae: 5257.9839
Epoch 95/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5202.7490 - mae: 5202.7490
Epoch 96/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5143.5610 - mae: 5143.5610
Epoch 97/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5079.3457 - mae: 5079.3457
Epoch 98/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5015.6885 - mae: 5015.6885
Epoch 99/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4945.7588 - mae: 4945.7588
Epoch 100/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4872.9370 - mae: 4872.9370
Epoch 101/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4795.7207 - mae: 4795.7207
Epoch 102/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4713.6152 - mae: 4713.6152
Epoch 103/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4628.7759 - mae: 4628.7759
Epoch 104/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4539.9995 - mae: 4539.9995
Epoch 105/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4447.6279 - mae: 4447.6279
Epoch 106/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4360.3687 - mae: 4360.3687
Epoch 107/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4273.3062 - mae: 4273.3062
Epoch 108/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4185.9385 - mae: 4185.9385
Epoch 109/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4104.2256 - mae: 4104.2256
Epoch 110/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4032.1277 - mae: 4032.1277
Epoch 111/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3979.4351 - mae: 3979.4351
Epoch 112/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3939.6831 - mae: 3939.6831
Epoch 113/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3905.0486 - mae: 3905.0486
Epoch 114/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3877.8054 - mae: 3877.8054
Epoch 115/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3859.1428 - mae: 3859.1428
Epoch 116/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3844.9746 - mae: 3844.9746
Epoch 117/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3830.3286 - mae: 3830.3286
Epoch 118/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3819.9617 - mae: 3819.9617
Epoch 119/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3811.2129 - mae: 3811.2129
Epoch 120/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3803.7432 - mae: 3803.7432
Epoch 121/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3798.1826 - mae: 3798.1826
Epoch 122/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3791.9458 - mae: 3791.9458
Epoch 123/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3787.1067 - mae: 3787.1067
Epoch 124/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3782.1821 - mae: 3782.1821
Epoch 125/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3779.5095 - mae: 3779.5095
Epoch 126/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3775.7202 - mae: 3775.7202
Epoch 127/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3774.1616 - mae: 3774.1616
Epoch 128/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3770.4160 - mae: 3770.4160
Epoch 129/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3766.6575 - mae: 3766.6575
Epoch 130/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3764.4502 - mae: 3764.4502
Epoch 131/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3761.9492 - mae: 3761.9492
Epoch 132/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3759.5999 - mae: 3759.5999
Epoch 133/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3757.8564 - mae: 3757.8564
Epoch 134/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3755.5798 - mae: 3755.5798
Epoch 135/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3752.7747 - mae: 3752.7747
Epoch 136/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3749.7893 - mae: 3749.7893
Epoch 137/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3747.9373 - mae: 3747.9373
Epoch 138/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3746.2786 - mae: 3746.2786
Epoch 139/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3744.1399 - mae: 3744.1399
Epoch 140/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3741.9973 - mae: 3741.9973
Epoch 141/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3738.9697 - mae: 3738.9697
Epoch 142/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3737.6025 - mae: 3737.6025
Epoch 143/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3736.6941 - mae: 3736.6941
Epoch 144/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3733.3228 - mae: 3733.3228
Epoch 145/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3730.6851 - mae: 3730.6851
Epoch 146/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3729.9585 - mae: 3729.9585
Epoch 147/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3728.1460 - mae: 3728.1460
Epoch 148/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3725.8015 - mae: 3725.8015
Epoch 149/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3723.3264 - mae: 3723.3264
Epoch 150/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3722.1885 - mae: 3722.1885
Epoch 151/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3720.0442 - mae: 3720.0442
Epoch 152/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3717.7991 - mae: 3717.7991
Epoch 153/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3715.7107 - mae: 3715.7107
Epoch 154/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3713.3533 - mae: 3713.3533
Epoch 155/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3712.0952 - mae: 3712.0952
Epoch 156/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3710.6636 - mae: 3710.6636
Epoch 157/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3707.9150 - mae: 3707.9150
Epoch 158/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3703.6440 - mae: 3703.6440
Epoch 159/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3701.1663 - mae: 3701.1663
Epoch 160/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3699.0425 - mae: 3699.0425
Epoch 161/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3696.7546 - mae: 3696.7546
Epoch 162/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3697.5330 - mae: 3697.5330
Epoch 163/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3696.0266 - mae: 3696.0266
Epoch 164/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3693.1641 - mae: 3693.1641
Epoch 165/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3691.7388 - mae: 3691.7388
Epoch 166/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3688.4890 - mae: 3688.4890
Epoch 167/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3685.6824 - mae: 3685.6824
Epoch 168/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3683.4692 - mae: 3683.4692
Epoch 169/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3681.1985 - mae: 3681.1985
Epoch 170/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3677.3777 - mae: 3677.3777
Epoch 171/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3676.3279 - mae: 3676.3279
Epoch 172/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3675.1538 - mae: 3675.1538
Epoch 173/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3674.8008 - mae: 3674.8008
Epoch 174/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3672.6750 - mae: 3672.6750
Epoch 175/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3669.4043 - mae: 3669.4043
Epoch 176/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3668.1318 - mae: 3668.1318
Epoch 177/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3666.0925 - mae: 3666.0925
Epoch 178/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3662.7769 - mae: 3662.7769
Epoch 179/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3660.8730 - mae: 3660.8730
Epoch 180/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3657.5664 - mae: 3657.5664
Epoch 181/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3657.6821 - mae: 3657.6821
Epoch 182/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3658.0298 - mae: 3658.0298
Epoch 183/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3652.0667 - mae: 3652.0667
Epoch 184/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3648.7534 - mae: 3648.7534
Epoch 185/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3646.4148 - mae: 3646.4148
Epoch 186/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3643.8442 - mae: 3643.8442
Epoch 187/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3642.4080 - mae: 3642.4080
Epoch 188/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3642.8118 - mae: 3642.8118
Epoch 189/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3641.0249 - mae: 3641.0249
Epoch 190/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3635.0217 - mae: 3635.0217
Epoch 191/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3633.4172 - mae: 3633.4172
Epoch 192/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3634.8979 - mae: 3634.8979
Epoch 193/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3631.1411 - mae: 3631.1411
Epoch 194/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3631.4624 - mae: 3631.4624
Epoch 195/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3624.6843 - mae: 3624.6843
Epoch 196/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3622.8074 - mae: 3622.8074
Epoch 197/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3622.9387 - mae: 3622.9387
Epoch 198/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3618.0833 - mae: 3618.0833
Epoch 199/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3618.2959 - mae: 3618.2959
Epoch 200/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3612.7202 - mae: 3612.7202
Epoch 201/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3611.1897 - mae: 3611.1897
Epoch 202/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3609.2805 - mae: 3609.2805
Epoch 203/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3606.4438 - mae: 3606.4438
Epoch 204/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3604.6975 - mae: 3604.6975
Epoch 205/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3600.7063 - mae: 3600.7063
Epoch 206/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3600.1895 - mae: 3600.1895
Epoch 207/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3596.6799 - mae: 3596.6799
Epoch 208/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3592.8408 - mae: 3592.8408
Epoch 209/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3592.1138 - mae: 3592.1138
Epoch 210/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3587.4377 - mae: 3587.4377
Epoch 211/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3585.8679 - mae: 3585.8679
Epoch 212/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3582.2917 - mae: 3582.2917
Epoch 213/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3578.7598 - mae: 3578.7598
Epoch 214/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3577.8110 - mae: 3577.8110
Epoch 215/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3578.8918 - mae: 3578.8918
Epoch 216/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3579.2947 - mae: 3579.2947
Epoch 217/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3579.2690 - mae: 3579.2690
Epoch 218/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3571.2578 - mae: 3571.2578
Epoch 219/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3569.0840 - mae: 3569.0840
Epoch 220/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3567.0234 - mae: 3567.0234
Epoch 221/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3566.0938 - mae: 3566.0938
Epoch 222/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3562.9836 - mae: 3562.9836
Epoch 223/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3560.9150 - mae: 3560.9150
Epoch 224/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3560.3950 - mae: 3560.3950
Epoch 225/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3557.0222 - mae: 3557.0222
Epoch 226/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3555.1472 - mae: 3555.1472
Epoch 227/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3553.9553 - mae: 3553.9553
Epoch 228/500
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3552.0010 - mae: 3552.0010
Epoch 229/500

In [ ]:
insurance_model.evaluate(xtest, ytest)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 3163.8560 - mae: 3163.8560

[3163.85595703125, 3163.85595703125]

In [2]:
pd.DataFrame(history.history).plot()
plt.ylabel('loss')
plt.xlabel('epochs')

NameError: name 'pd' is not defined

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
insurance = pd.read_csv('/content/insurance.csv')

In [8]:
insurance

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [10]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

In [11]:
ct = make_column_transformer(
    (MinMaxScaler(), ['age','bmi','children']),
    (OneHotEncoder(handle_unknown='ignore'), ['sex', 'smoker', 'region'])
)

x = insurance.drop('charges', axis = 1)
y = insurance['charges']

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state = 42)

ct.fit(xtrain)

xtrain_normal = ct.transform(xtrain)
xtest_normal = ct.transform(xtest)

In [16]:
xtrain_normal[0]

array([0.60869565, 0.10734463, 0.4       , 1.        , 0.        ,
       1.        , 0.        , 0.        , 1.        , 0.        ,
       0.        ])

In [17]:
xtrain.shape, xtrain_normal.shape

((1070, 6), (1070, 11))

In [18]:
import tensorflow as tf

In [28]:
insurance_model_2 = tf.keras.Sequential([
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
])

insurance_model_2.compile(loss=tf.keras.losses.mae,
                          optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
                          metrics=['mae'])

insurance_model_2.fit(xtrain_normal, ytrain, epochs=200)

Epoch 1/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 13342.6572
Epoch 2/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 13332.1318
Epoch 3/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 13307.4932
Epoch 4/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 13257.8838
Epoch 5/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 13171.8730
Epoch 6/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 13038.4277
Epoch 7/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 12847.1934
Epoch 8/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 12588.3984
Epoch 9/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 12252.3115
Epoch 10/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 11836.0703
Epoch 11/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 11353.2666
Epoch 12/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 10848.8330
Epoch 13/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 10347.0391
Epoch 14/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 9855.2539
Epoch 15/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 9393.6084
Epoch 16/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 8996.3750
Epoch 17/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 8657.3516
Epoch 18/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 8391.2891
Epoch 19/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 8197.5156
Epoch 20/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 8054.3096
Epoch 21/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7958.9448
Epoch 22/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7884.7627
Epoch 23/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7827.0259
Epoch 24/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7776.4385
Epoch 25/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7729.1416
Epoch 26/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7684.3418
Epoch 27/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7641.0195
Epoch 28/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7596.9185
Epoch 29/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7551.7886
Epoch 30/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7507.2021
Epoch 31/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7461.9644
Epoch 32/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7416.1079
Epoch 33/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7367.3364
Epoch 34/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7316.8193
Epoch 35/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7267.1611
Epoch 36/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7215.4463
Epoch 37/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7162.3931
Epoch 38/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7109.7808
Epoch 39/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 7052.7666
Epoch 40/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 6993.0898
Epoch 41/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 6931.6079
Epoch 42/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 6868.4155
Epoch 43/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 6802.8667
Epoch 44/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 6734.4648
Epoch 45/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 6662.1890
Epoch 46/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 6586.8257
Epoch 47/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 6508.9067
Epoch 48/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 6429.0957
Epoch 49/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 6343.8423
Epoch 50/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 6254.5464
Epoch 51/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 6160.3975
Epoch 52/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 6063.9834
Epoch 53/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 5961.9614
Epoch 54/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 5854.9639
Epoch 55/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 5744.4058
Epoch 56/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 5626.1064
Epoch 57/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 5508.6274
Epoch 58/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 5388.4629
Epoch 59/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 5265.5298
Epoch 60/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 5135.7515
Epoch 61/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 5008.2241
Epoch 62/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 4873.1567
Epoch 63/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 4741.8101
Epoch 64/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 4609.1816
Epoch 65/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 4486.9839
Epoch 66/200
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 4373.9375
Epoch 67/200
22/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - f1_score: 1.9999 - loss: 4906.5905

KeyboardInterrupt:

In [26]:
insurance_model_2.evaluate(xtest_normal, ytest)

9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - loss: 3165.9185 - mae: 3165.9185

[3165.91845703125, 3165.91845703125]